# NumPy

Para iniciar a etapa de análise de dados, é essencial conhecer as principais ferramentas utilizadas nesse processo. A biblioteca NumPy é uma das mais fundamentais na base do ecossistema de ciência de dados em Python. Voltada para o trabalho com arrays e operações numéricas de alta performance, ela fornece estruturas eficientes e funções otimizadas para cálculos matemáticos e manipulação de dados, servindo como suporte para diversas outras bibliotecas e aplicações analíticas.

## Arrays e Listas

Arrays são estruturas fundamentais em ciência de dados por permitirem o armazenamento e a manipulação eficiente de grandes volumes de dados numéricos. Eles tornam cálculos matemáticos mais rápidos e simples graças às operações vetorizadas.

- **Array Numpy**

    - É uma estrutura de dados que armazena elementos de um único tipo, o que resulta em maior eficiência de memória e desempenho em comparação com listas.

    - Permite realizar operações matemáticas de forma vetorizada (aplicar operações matemáticas em todos os elementos do array ao mesmo tempo), sem a necessidade de loops.

    - Caso receba elementos de tipos diferentes, converte todos para o tipo mais genérico. Por exemplo, se houver inteiros e uma string, todos os elementos serão convertidos para string.

- **Listas**

    - Uma lista é uma das estruturas de dados mais fundamentais do Python.

    - Permite armazenar qualquer tipo de dado: números, strings, outras listas, objetos, etc., mesmo misturados entre si.

    - É uma estrutura mutável, ou seja, os elementos podem ser alterados, adicionados ou removidos após a criação da lista.

Em Python, listas são criadas utilizando colchetes `[]`, enquanto arrays do NumPy são criados com a função `np.array([])`. Veja abaixo um exemplo de como criar ambos com os mesmos valores:

In [ ]:
import numpy as np 

# Criando uma lista
lista = [1, 2, 3, 4, 5, 6]

# Criando um array numpy
array = np.array([1, 2, 3, 4, 5, 6])

## Diferenças entre Arrays e Listas

- **Tipos de Dados**

    - **Listas:** Podem conter elementos de tipos diferentes (por exemplo, números, strings, listas dentro de listas).

    - **Arrays:** Armazenam elementos de um único tipo. Se houver elementos de tipos diferentes, o NumPy converte todos para o tipo mais genérico (por exemplo, tudo vira string).

- **Operações Matemáticas**

    - **Listas:** Não suportam operações matemáticas diretamente sobre todos os elementos. É necessário iterar com `for` ou usar `list comprehensions`.

    - **Arrays:** Permitem realizar operações matemáticas diretamente de forma vetorizada, ou seja, operando sobre todos os elementos ao mesmo tempo (ex: `array + 2`, `array * 3`).

- **Funcionalidades**

    - **Listas:** São versáteis, mas limitadas para operações numéricas. Precisam de código adicional ou bibliotecas externas para estatísticas e álgebra linear.

    - **Arrays:** Têm diversas funções integradas otimizadas, como `sum()`, `mean()`, `std()`, `dot()`, além de suporte a operações entre matrizes, broadcasting, entre outras.

- **Desempenho**

    - **Listas:** Mais lentas e menos eficientes em memória para grandes volumes de dados numéricos.
    
    - **Arrays:** Mais rápidos e eficientes, especialmente em cálculos com grandes conjuntos de dados.

## Exemplo de Operações Matemáticas

Abaixo será apresentada a diferença entre realizar uma operação matemática utilizando listas e arrays, para evidenciar o contraste entre ambos.

In [ ]:
# Operações matemáticas dentro de uma lista
lista = [1, 2, 3, 4, 5]
operacao_for = [] # criando uma nova lista para armazenar os novos valores
for numero in lista: # usando for
    operacao_for.append(numero + 1) # somar um em cada valor da lista

operacao_list_comprehension = [numero + 1 for numero in lista] # usando list comprehension

print(f"""Lista sem operação matemática: {lista}
Lista com operação matemática usando for: {operacao_for}
Lista com operação matemática usando for: {operacao_list_comprehension}""")

Lista sem as operações matemáticas: [1, 2, 3, 4, 5]
Lista com operação matemática usando for: [2, 3, 4, 5, 6]
Lista com operação matemática usando for: [2, 3, 4, 5, 6] 


In [ ]:
# Operações matemáticas dentro de um array
import numpy as np
array = np.array([1, 2, 3, 4, 5])
array_operacao = array + 1 # criando um novo array apenas com a operação matemática

print(f"""Array sem operação matemática: {array}
Array com operação matemática: {array_operacao}""")

Array sem operação matemática: [1 2 3 4 5]
Array com operação matemática: [2 3 4 5 6]


## Indexação e Slicing com Arrays

- Assim como nas listas, também é possível acessar elementos de arrays utilizando indexação e slicing. Abaixo estão alguns exemplos que demonstram como fazer isso com arrays NumPy:

In [11]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

print(f'Primeiro exemplo: {array[2]}') # pegando o índice 2
print(f'Segundo exemplo: {array[0:3]}') # pegando do índice 0 até o índice 2
print(f'Terceiro exemplo: {array[0:-1:2]}') # pegando do índice 0 até o penúltimo índice indo de 2 em 2
print(f'Quarto exemplo: {array[::-1]}') # inverte a lista

Primeiro exemplo: 3
Segundo exemplo: [1 2 3]
Terceiro exemplo: [1 3]
Quarto exemplo: [5 4 3 2 1]


## Funções Básicas de um Array

- Assim como ocorre com listas, o NumPy oferece diversas funções que facilitam a realização de operações matemáticas dentro de um array.

    - `np.sum()` →  Soma todos os elementos de um array.

    - `np.mean()` → Calcula a média dos elementos do array.

    - `np.max()` → Retorna o maior valor presente no array.

    - `np.min()` → Retorna o menor valor presente no array.

    - `np.sort()` → Ordena os valores do array em ordem crescente.

    - `np.dot()` → Realiza o produto escalar entre dois arrays, multiplicando elemento por elemento e somando os resultados.

    - `np.argmax()` → Retorna o índice do maior valor no array.

    - `np.argmin()` → Retorna o índice do menor valor no array.

    - `np.count_nonzero()` → Conta quantos valores do array são diferentes de zero. Pode ser usada para verificar quantos elementos são `True` após aplicar uma determinada condição.

    - `np.unique()` → Retorna os elementos únicos de um array, removendo duplicatas.

- Abaixo, serão apresentados exemplos práticos para demonstrar o funcionamento de cada uma dessas funções do NumPy.

In [24]:
import numpy as np

salarios = np.array([2500, 3200, 2800, 4000, 3500, 2200, 2700, 3100, 3300, 4500, 1900, 2200, 2500, 4200, 3200])

soma_salarios = np.sum(salarios) # soma todos os salarios do array
media_salarios = np.mean(salarios) # calcula a media salarial

maior_salario = np.max(salarios) # pega o maior salário do array
menor_salario = np.min(salarios) # pega o menor salário do array

salarios_ordenados = np.sort(salarios) # ordena em ordem crescente

# Produto escalar entre salários e um vetor de meses
meses = np.array([3] * len(salarios)) # cria um array do mesmo tamanho do array 'salários' com apenas o número 3
salario_total_trimestre = np.dot(salarios, meses) # saber quanto a empresa irá gastar com o salário de todos os funcionários no trimestre

maior_indice = np.argmax(salarios) # pega o índice que possui o maior valor de salário
menor_indice = np.argmin(salarios) # pega o índice que possui o menor valor de salário

acima_da_media = np.count_nonzero(salarios > media_salarios) # calcula a quantidade de funcionários que recebem acima da média salarial

# Analisando os valores únicos de cada salário
# valores_salario armazena os elementos únicos de um array
# contagem_salario armazena o número de vezes que cada elemento único aparece
valores_salario, contagem_salario = np.unique(salarios, return_counts=True) # o return_counts=True permite que a função np.unique() também retorne quantas vezes cada valor único aparece

# Também é possível colocar expressões dentro da função np.unique():
# Analisando os elementos únicos de um array onde o salário é maior que a média (True ou False)
valores_maior_media, contagem_maior_media = np.unique(salarios > media_salarios, return_counts=True)

# --- PRINTS ---
print(f'Soma dos salários: {soma_salarios}')
print(f'Média salarial: {media_salarios:.2f}') # apenas duas casas depois da vírgula
print(f'Maior salário: {maior_salario}')
print(f'Menor salário: {menor_salario}')
print(f'Salários ordenados em ordem crescente: {salarios_ordenados}')
print(f'Produto escalar para calcular o gasto total no trimestre: {salario_total_trimestre}')
print(f'Índice do maior salário: {maior_indice}')
print(f'Índice do menor salário: {menor_indice}')
print(f'Funcionários acima da média salarial: {acima_da_media}')
print(f'Valores únicos dos salários: {valores_salario}')
print(f'Quantidade de vezes que cada salário aparece: {contagem_salario}')
print(f'Valores únicos (acima da média): {valores_maior_media}')
print(f'Contagem de True/False (acima da média): {contagem_maior_media}')

Soma dos salários: 45800
Média salarial: 3053.33
Maior salário: 4500
Menor salário: 1900
Salários ordenados em ordem crescente: [1900 2200 2200 2500 2500 2700 2800 3100 3200 3200 3300 3500 4000 4200
 4500]
Produto escalar para calcular o gasto total no trimestre: 137400
Índice do maior salário: 9
Índice do menor salário: 10
Funcionários acima da média salarial: 8
Valores únicos dos salários: [1900 2200 2500 2700 2800 3100 3200 3300 3500 4000 4200 4500]
Quantidade de vezes que cada salário aparece: [1 2 2 1 1 1 2 1 1 1 1 1]
Valores únicos (acima da média): [False  True]
Contagem de True/False (acima da média): [7 8]


## Funções Estatísticas

O NumPy oferece diversas funções estatísticas que facilitam na análise e interpretação de dados, como por exemplo:

- **Mediana:** A mediana é o valor que divide um conjunto de dados em duas partes iguais, sendo um importante indicador de tendência central. Para encontrá-la, os dados devem ser ordenados de forma crescente ou decrescente, e o valor central é selecionado. Se houver um número ímpar de dados, a mediana é o valor exatamente do meio, se houver um número par, a mediana é a média dos dois valores centrais. No NumPy, a mediana é calculada com a função `np.median(dados)`.

- **Percentil:** O percentil é uma medida que indica a posição relativa de um valor dentro de um conjunto de dados, representando a porcentagem de valores abaixo desse dado. Por exemplo, o percentil 50 (também conhecido como mediana) divide os dados em duas partes iguais, com 50% dos valores abaixo dele e 50% acima. Para calcular percentis no NumPy, usa-se a função `np.percentile(dados, percentil)`, onde `percentil` é o valor desejado `(como 25, 50, 75, etc.)`.

- **Desvio Padrão:** O desvio padrão mede a dispersão dos dados em relação à média. Um desvio padrão elevado indica que os dados estão mais espalhados, enquanto um valor baixo indica que estão mais concentrados em torno da média. Para calcular o desvio padrão no NumPy, utiliza-se a função `np.std(dados)`.

- **Variância:** A variância também é uma medida de dispersão, que reflete a média dos quadrados das diferenças entre cada valor e a média. Ela mostra o quão distantes os valores estão da média, sendo um indicador importante de variabilidade. A variância é calculada no NumPy com a função `np.var(dados)`.

Abaixo, são apresentados exemplos de como utilizar cada uma dessas funções estatísticas:

In [28]:
import numpy as np

# array contendo números floats de venda de produtos
vendas = np.array([1020.50, 875.90, 1340.75, 990.00, 1205.30, 1570.60, 1115.20, 980.40, 1435.80, 1260.00])

mediana = np.median(vendas) # cálculo da mediana
percentil = np.percentile(vendas, 25) # cálculo do percentil 25, que representa o valor abaixo do qual estão 25% dos dados (1º quartil)
desvio_padrao = np.std(vendas) # cálculo do desvio padrão
variancia = np.var(vendas) # cálculo da variância

print(f'Mediana: {mediana}')
print(f'Percentil 25: {percentil}')
print(f'Desvio padrão: {desvio_padrao}')
print(f'Variância: {variancia}')

Mediana: 1160.25
Percentil 25: 997.625
Desvio padrão: 211.8810591463994
Variância: 44893.583224999995


## Geração de Números Aleatórios

- O NumPy permite gerar números aleatórios de forma simples e eficiente. Isso é especialmente útil para realizar testes, criar simulações ou gerar dados fictícios de maneira controlada, por meio do uso de `seeds`.

- Para começar, é necessário criar um gerador de números aleatórios com `np.random.default_rng()`. Esse gerador será usado para controlar a geração dos números e permitirá o uso de `seeds`, garantindo a reprodutibilidade dos dados gerados.

- A `seed` serve para definir um ponto de partida fixo para o gerador de números aleatórios. Sempre que a mesma `seed` for utilizada, os mesmos números serão gerados, o que é essencial para manter consistência em testes e simulações.

- Para gerar os números aleatórios, utiliza-se o método `rng.random()`, que gera números do tipo float no intervalo de 0 a 1. Também é possível definir quantos números deseja gerar e manipular o intervalo multiplicando os valores gerados. (*Exemplo 1*)

    - O "truque" para transformar esses números (entre 0 e 1) em um intervalo personalizado, como por exemplo entre 5 e 10, é utilizar a fórmula de transformação de intervalo:

        $$\text{novo\_valor} = \text{valor\_original} \times (b - a) + a$$

        - `valor_original` é o número gerado entre 0 e 1

        - `a` é o valor mínimo desejado (ex: 5)

        - `b` é o valor máximo desejado (ex: 10)

- Além disso, o método `rng.integers()` pode ser utilizado quando se deseja gerar números inteiros aleatórios dentro de um intervalo específico. Com ele, é possível definir tanto o valor mínimo quanto o máximo, além da quantidade de números desejada. (*Exemplo 2*)

- Também é possível gerar um array de números aleatórios com base em uma média e um desvio padrão específicos. Para isso, utiliza-se o método `rng.normal()`, que gera valores seguindo uma distribuição normal (ou gaussiana). (*Exemplo 3*)

Abaixo, são apresentados três exemplos de uso:

In [ ]:
import numpy as np

# Exemplo 1: Utilizando geração de floats e sem seed definida:

rng = np.random.default_rng() # não utiliza número de seed, então a cada vez que rodar o código, novos números são gerados
float_aleatorios = rng.random(10) * (10 - 5) + 5 # gera 10 números aleatórios entre 5 e 10
print(f'Array de floats aleatórios: \n{float_aleatorios}')

Array de floats aleatórios: 
[5.34227059 5.96915032 8.97136944 8.3847519  8.3339419  5.29951407
 8.17666527 6.22855442 9.58369772 8.12810095]


In [2]:
import numpy as np

# Exemplo 2: Utilizando geração de inteiros

rng = np.random.default_rng(seed=42) # utiliza número de seed, então os números sempre serão os mesmos
inteiros_aleatorios = rng.integers(low=100, high=200, size=10) # gera 10 números aleatórios entre 100 e 201
print(f'Array de inteiros aleatórios: \n{inteiros_aleatorios}')

Array de inteiros aleatórios: 
[108 177 165 143 143 185 108 169 120 109]


In [1]:
import numpy as np

# Exemplo 3: Utilizando floats aleatórios levando em consideração uma média um desvio padrão

media = 7
desvio_padrao = 1

rng = np.random.default_rng(seed=43)
normal_aleatorios = rng.normal(loc=media, scale=desvio_padrao, size=10) # gera 10 números aleatórios, onde loc é a média, e scale é o desvio padrão
print(f'Array de floats aleatórios levando em consideração uma média um desvio padrão: \n{normal_aleatorios}')

Array de floats aleatórios levando em consideração uma média um desvio padrão: 
[7.24422951 7.67817832 6.41447062 6.09132688 5.00816179 7.97162298
 7.0166573  7.20573134 6.21640512 8.22649803]


## Função Where

- A função `np.where()` é uma ferramenta poderosa do NumPy para realizar seleções condicionais em arrays de forma vetorizada e eficiente.

- Ela funciona como um `if` para arrays: em vez de usar loops para verificar condição por condição, a função aplica a lógica a todo o array de uma vez.

- Inicialmente, a função `np.where()` retorna apenas os índices dos elementos que satisfazem a condição. No entanto, é possível utilizá-la em conjunto com o próprio array para obter os valores correspondentes à condição verdadeira. (*Exemplo 1*)

- Além de verificar uma condição, o `np.where()` também pode ser usado para alterar os valores do array, definindo diferentes resultados para quando a condição for verdadeira ou falsa. (*Exemplo 2*)

- Também é possível utilizar condições com `and` e `or`, usando os operadores `&` e `|`, semelhantes aos da linguagem C. (*Exemplo 3*)

- A negação de uma condição pode ser feita com o operador `~`, que inverte o resultado lógico, retornando o oposto da condição original. (*Exemplo 4*)

Abaixo, serão apresentados quatro exemplos de uso do `np.where()` com diferentes abordagens:

In [4]:
import numpy as np

# Exemplo 1: Retornando os índices e os valores após uma determinada condição

temperaturas = np.array([22.5, 25.0, 27.3, 30.1, 21.0, 23.7, 26.4, 28.9, 29.5, 24.1, 25.6, 31.2, 32.8, 27.0, 20.5, 26.1, 22.8, 24.9, 28.0, 30.5]) # array de temperaturas diárias em °C
media = temperaturas.mean()

# Identificar quais são os dias em que a temperatura esteve acima da média
temperaturas_acima_indice = np.where(temperaturas > media)[0] # retorna os índices e o [0] ao lado faz com que retorne um array e não uma tupla
temperaturas_acima_valor = temperaturas[np.where(temperaturas > media)] # retorna os valores

print(f'Array das temperaturas: {temperaturas}')
print(f'Média das temperaturas: {media:.3f}\n')
print(f'Índice das temperaturas maiores que a média: {temperaturas_acima_indice}')
print(f'Valores das temperaturas maiores que a média: {temperaturas_acima_valor}')

Array das temperaturas: [22.5 25.  27.3 30.1 21.  23.7 26.4 28.9 29.5 24.1 25.6 31.2 32.8 27.
 20.5 26.1 22.8 24.9 28.  30.5]
Média das temperaturas: 26.395

Índice das temperaturas maiores que a média: [ 2  3  6  7  8 11 12 13 18 19]
Valores das temperaturas maiores que a média: [27.3 30.1 26.4 28.9 29.5 31.2 32.8 27.  28.  30.5]


In [5]:
import numpy as np

# Exemplo 2: Mudando os valores do array de acordo com a condição

salarios = np.array([2000, 5000, 6100, 9000, 2200, 3500, 4100, 5500, 6000, 3600, 4800, 9800, 7700, 6200, 2000, 4100, 2200, 3800, 5200, 7000]) # array de salários dos funcionários
media = salarios.mean() # media salarial

# Caso o salário esteja acima da média (True) → muda para 'acima da média'
# Caso o salário esteja abaixo da média (False) → muda para 'abaixo da média'
salarios_acima = np.where(salarios > media, 'acima da média', 'abaixo da média')

# Caso o salário esteja abaixo da média (True) → aumenta 10% no valor 
# Caso o salário esteja acima da média (False) → mantém o mesmo valor
salarios_bonus = np.where(salarios < media, salarios * 1.1, salarios)

print(f'Array dos salários antes da mudança: {salarios}')
print(f'Média dos salários: {media}\n')
print(f'Array dos salários com mudança de nome: {salarios_acima}\n')
print(f'Array dos Salários com bônus: {salarios_bonus}')

Array dos salários antes da mudança: [2000 5000 6100 9000 2200 3500 4100 5500 6000 3600 4800 9800 7700 6200
 2000 4100 2200 3800 5200 7000]
Média dos salários: 4990.0

Array dos salários com mudança de nome: ['abaixo da média' 'acima da média' 'acima da média' 'acima da média'
 'abaixo da média' 'abaixo da média' 'abaixo da média' 'acima da média'
 'acima da média' 'abaixo da média' 'abaixo da média' 'acima da média'
 'acima da média' 'acima da média' 'abaixo da média' 'abaixo da média'
 'abaixo da média' 'abaixo da média' 'acima da média' 'acima da média']

Array dos Salários com bônus: [2200. 5000. 6100. 9000. 2420. 3850. 4510. 5500. 6000. 3960. 5280. 9800.
 7700. 6200. 2200. 4510. 2420. 4180. 5200. 7000.]


In [ ]:
import numpy as np

# Exemplo 3: Utilizando mais de uma condição

salarios = np.array([2000, 5000, 6100, 9000, 2200, 3500, 4100, 5500, 6000, 3600, 4800, 9800, 7700, 6200, 2000, 4100, 2200, 3800, 5200, 7000]) # array de salários dos funcionários

# Caso o salário seja maior ou igual a 4000 E menor ou igual a 8000, recebe um aumento de 10%
salarios_primeiro_aumento = np.where((salarios >= 4000) & (salarios <= 8000), salarios * 1.1, salarios) # utilizando a condição AND (&)

# Caso o salário seja menor que 4000 OU maior que 8000, recebe um aumento de 20%
# Lembrando que caso a condição seja False, ele retorna o salário da condição de cima (dos 10%), isso para não dar conflito de valores e receber dois aumentos
salarios_aumento_total = np.where((salarios < 4000) | (salarios > 8000), salarios * 1.2, salarios_primeiro_aumento) # utilizando a condição OR (|)

print(f'Array dos salários antes do aumento: {salarios}\n')
print(f'Array dos salários depois dos aumentos de 10% e 20%: {salarios_aumento_total}')

Array dos salários antes do aumento: [2000 5000 6100 9000 2200 3500 4100 5500 6000 3600 4800 9800 7700 6200
 2000 4100 2200 3800 5200 7000]

Array dos salários depois dos aumentos de 10% e 20%: [ 2400.  5500.  6710. 10800.  2640.  4200.  4510.  6050.  6600.  4320.
  5280. 11760.  8470.  6820.  2400.  4510.  2640.  4560.  5720.  7700.]


In [7]:
import numpy as np

# Exemplo 4: Utilizando uma negação à condição atual

rng = np.random.default_rng(seed=1) # criando uma seed para os números serem sempre os mesmos
numeros = rng.integers(low=1, high=11, size=20) # array tamanho 20, podendo ir de 1 até 10

numeros_menores_5 = numeros[np.where(~(numeros > 5))] # seleciona os números menores ou iguais a 5 usando negação da condição com ~

print(f'Array com números de 1 a 10: {numeros}\n')
print(f'Array com números menores ou iguais a 5: {numeros_menores_5}')

Array com números de 1 a 10: [ 5  6  8 10  1  2  9 10  3  4  9  5  3  9  3  5  7  6  1  1]

Array com números menores ou iguais a 5: [5 1 2 3 4 5 3 3 5 1 1]


## Função Reshape

- A função `np.reshape()` é usada para alterar a estrutura de um array, reorganizando seus elementos em uma nova forma (dimensão). Por exemplo, se você possui os valores de temperatura registrados durante 14 dias consecutivos, pode reorganizar esses dados em uma matriz 2x7 (2 semanas, 7 dias cada), facilitando a análise por semana.

- Em essência, o `np.reshape()` transforma um array unidimensional em uma matriz ou altera suas dimensões conforme a necessidade, desde que o número total de elementos continue o mesmo. (*Exemplo 1*)

- É possível verificar o número de dimensões e o formato de um array utilizando os seguintes atributos (considerando que dados representa um array qualquer):

    - `np.ndim(dados)` → retorna o número de dimensões (ou eixos) do array. (*Exemplo 1*)

    - `np.shape(dados)` → retorna uma tupla com o tamanho de cada dimensão, ou seja, o formato do array (ex: número de linhas e colunas). (*Exemplo 1*)

- Se você já souber quantas linhas ou colunas deseja e quiser que o NumPy calcule automaticamente a outra dimensão, pode usar -1 como valor. O NumPy ajustará essa dimensão com base no tamanho total do array original. É importante lembrar que o valor informado precisa ser compatível com a quantidade total de elementos. (*Exemplo 2*)

- Assim como em uma matriz, é possível acessar ou selecionar elementos de um array utilizando seus respectivos índices, inclusive combinando linhas e colunas em arrays multidimensionais. (*Exemplo 3*)

- Para realizar operações como média, soma, mínimo, máximo, entre outras em arrays multidimensionais, o parâmetro `axis` dentro da função é essencial. O `axis=0` aplica a operação ao longo das colunas (por linha), e o `axis=1` aplica ao longo das linhas (por coluna). (*Exemplo 4*)

    ![Reshape-Axis](imagens/1.%20reshape_axis.jpg)

In [25]:
import numpy as np

# Exemplo 1: Utilizando a função reshape para reorganizar a temperatura nas últimas duas semanas e calcular sua dimensão e formato

import numpy as np

# Realizando o Reshape
temperaturas = np.array([22.5, 23.1, 21.9, 24.3, 25.0, 23.8, 22.7, 24.5, 25.2, 23.9, 22.8, 24.0, 25.5, 23.6]) # temperaturas dos últimos 14 dias
temperaturas_reshape = np.reshape(temperaturas, (2, 7)) # 2 semanas, 7 dias cada

# Calculando a dimensão e o formato do Array de temperaturas sem reshape
dimensao = np.ndim(temperaturas) # calculando a dimensão sem reshape
formato = np.shape(temperaturas) # calculando o formato sem reshape

# Calculando a dimensão e o formato do Array de temperaturas com reshape
dimensao_reshape = np.ndim(temperaturas_reshape) # calculando a dimensão com reshape
formato_reshape = np.shape(temperaturas_reshape) # calculando o formato com reshape

print(f'Array com as temperaturas antes do reshape: {temperaturas}')
print(f'Array com as temperaturas depois do reshape: \n{temperaturas_reshape}\n') # separa em duas semanas diferentes
print(f'Dimensão do array sem reshape: {dimensao}')
print(f'Formato do array sem reshape: {formato}\n')
print(f'Dimensão do array com reshape: {dimensao_reshape}')
print(f'Formato do array com reshape: {formato_reshape}')

Array com as temperaturas antes do reshape: [22.5 23.1 21.9 24.3 25.  23.8 22.7 24.5 25.2 23.9 22.8 24.  25.5 23.6]
Array com as temperaturas depois do reshape: 
[[22.5 23.1 21.9 24.3 25.  23.8 22.7]
 [24.5 25.2 23.9 22.8 24.  25.5 23.6]]

Dimensão do array sem reshape: 1
Formato do array sem reshape: (14,)

Dimensão do array com reshape: 2
Formato do array com reshape: (2, 7)


In [27]:
import numpy as np

# Exemplo 2: Calculando automaticamente a outra dimensão
# É muito utilizado quando se tem um array com muitos números e não se sabe o número de linhas ou de colunas

temperaturas = np.array([22.5, 23.1, 21.9, 24.3, 25.0, 23.8, 22.7, 24.5, 25.2, 23.9, 22.8, 24.0, 25.5, 23.6]) # temperaturas dos últimos 14 dias

# Calculando a quantidade de colunas, onde já se tem a quantidade de linhas
temperaturas_reshape_linha = np.reshape(temperaturas, (2, -1))
formato_linha = np.shape(temperaturas_reshape_linha)

# Calculando a quantidade de linhas, onde já se tem a quantidade de colunas
temperaturas_reshape_coluna = np.reshape(temperaturas, (-1, 7))
formato_coluna = np.shape(temperaturas_reshape_coluna)
print(f'Array com as temperaturas antes do reshape: {temperaturas}\n')
print(f'Array com reshape sabendo o número de linhas: \n{temperaturas_reshape_linha}')
print(f'Formato do array sabendo o número de linhas: {formato_linha}\n')
print(f'Array com reshape sabendo o número de colunas: \n{temperaturas_reshape_coluna}')
print(f'Formato do array sabendo o número de colunas: {formato_coluna}')

Array com as temperaturas antes do reshape: [22.5 23.1 21.9 24.3 25.  23.8 22.7 24.5 25.2 23.9 22.8 24.  25.5 23.6]

Array com reshape sabendo o número de linhas: 
[[22.5 23.1 21.9 24.3 25.  23.8 22.7]
 [24.5 25.2 23.9 22.8 24.  25.5 23.6]]
Formato do array sabendo o número de linhas: (2, 7)

Array com reshape sabendo o número de colunas: 
[[22.5 23.1 21.9 24.3 25.  23.8 22.7]
 [24.5 25.2 23.9 22.8 24.  25.5 23.6]]
Formato do array sabendo o número de colunas: (2, 7)


In [22]:
import numpy as np

# Exemplo 3: Selecionando os valores de um array com reshape pelo índice

temperaturas = np.array([22.5, 23.1, 21.9, 24.3, 25.0, 23.8, 22.7, 24.5, 25.2, 23.9, 22.8, 24.0, 25.5, 23.6]) # temperaturas dos últimos 14 dias
temperaturas_reshape = np.reshape(temperaturas, (2, 7)) # 2 semanas, 7 dias cada

print(f'Primeira linha do array com reshape: {temperaturas_reshape[0]}')
print(f'Segunda linha do array com reshape: {temperaturas_reshape[1]}')
print(f'Primeiro elemento no array com reshape: {temperaturas_reshape[0][0]}')
print(f'Último elemento do array com reshape: {temperaturas_reshape[-1][-1]}')

Primeira linha do array com reshape: [22.5 23.1 21.9 24.3 25.  23.8 22.7]
Segunda linha do array com reshape: [24.5 25.2 23.9 22.8 24.  25.5 23.6]
Primeiro elemento no array com reshape: 22.5
Último elemento do array com reshape: 23.6


In [43]:
import numpy as np

# Exemplo 4: Realizando operações de acordo com o parâmetro axis

# Array com as notas de 5 alunos, sendo 3 provas para cada um
notas = np.array([7.5, 8.0, 6.5, 9.0, 7.0, 8.5, 6.0, 7.5, 8.0, 7.8, 6.9, 7.2, 8.4, 9.1, 7.5 ])
notas_reshape = np.reshape(notas, (3, 5)) # as provas são as linhas e os alunos são as colunas

# Calculando a soma
soma_cada_aluno = np.sum(notas_reshape, axis=0) # soma a nota de cada aluno (soma a coluna)
soma_notas = np.sum(notas_reshape, axis=1) # soma a nota de cada prova para todos os aluno (soma a linha)

# Calculando a média
media_cada_aluno = np.mean(notas_reshape, axis=0) # média da nota de cada aluno (soma a coluna)
media_notas = np.mean(notas_reshape, axis=1) # média da nota de cada prova para todos os alunos (soma a linha)

print(f'Array com as notas sem o reshape: {notas}')
print(f'Array com as notas com o reshape: \n{notas_reshape}\n')
print(f'Soma das notas de cada aluno: {soma_cada_aluno}')
print(f'Soma de todas as notas por prova: {soma_notas}\n')
print(f'Média das notas de cada aluno: {media_cada_aluno}')
print(f'Média de todas as notas por prova: {media_notas}')

Array com as notas sem o reshape: [7.5 8.  6.5 9.  7.  8.5 6.  7.5 8.  7.8 6.9 7.2 8.4 9.1 7.5]
Array com as notas com o reshape: 
[[7.5 8.  6.5 9.  7. ]
 [8.5 6.  7.5 8.  7.8]
 [6.9 7.2 8.4 9.1 7.5]]

Soma das notas de cada aluno: [22.9 21.2 22.4 26.1 22.3]
Soma de todas as notas por prova: [38.  37.8 39.1]

Média das notas de cada aluno: [7.63333333 7.06666667 7.46666667 8.7        7.43333333]
Média de todas as notas por prova: [7.6  7.56 7.82]
