# Resolução da Lista de Exercícios sobre NumPy

### Exercício 1: Aumento nos preços dos produtos

Dado um array com os preços de alguns produtos de uma loja, o dono decidiu aumentar o valor de todos os produtos em 20%. No entanto, o último produto da lista deve receber um aumento de 40% em vez de 20%.

**Tarefa:** Calcule o novo valor de cada produto após o reajuste, fazendo os cálculos duas vezes:

- Uma utilizando um array (NumPy)

- Outra utilizando uma lista comum (Python)

In [ ]:
import numpy as np

# Introdução
lista_precos = [50, 75, 30, 60, 90, 45, 80, 55, 100, 70] # Lista com os valores de cada produto
array_precos = np.array(lista_precos) # Array com os valores de cada produto

# Resolução do Exercício:

# Resolução da lista por list comprehension
list_comprehension_precos = [preco * 1.4 if i == (len(lista_precos) - 1) else preco * 1.2 for i, preco in enumerate(lista_precos)]

# Resolução da lista por for
for i in range(len(lista_precos)): # percorre o tamanho da lista pelo índice
    if i == (len(lista_precos) - 1): # se for o último elemento da lista
        lista_precos[i] *= 1.4 # aumento de 40%
    else: # se não for o último índice
        lista_precos[i] *= 1.2 # aumento de 20%

# Resolução do array
array_precos[-1] = array_precos[-1] * 1.4
array_precos[0:-1] = array_precos[0:-1] * 1.2

# Prints
print(f'Lista com os novos preços: \n{lista_precos}\n')
print(f'List Comprehension com os novos preços: \n{list_comprehension_precos}\n')
print(f'Array com os novos preços: \n{array_precos}')


Lista com os novos preços: 
[60.0, 90.0, 36.0, 72.0, 108.0, 54.0, 96.0, 66.0, 120.0, 98.0]

List Comprehension com os novos preços: 
[60.0, 90.0, 36.0, 72.0, 108.0, 54.0, 96.0, 66.0, 120.0, 98.0]

Array com os novos preços: 
[ 60  90  36  72 108  54  96  66 120  98]


### Exercício 2: Análise de Desempenho de Vendas
Dado um array com os valores de vendas realizadas por um grupo de vendedores durante um mês, resolva os seguintes itens:

- Calcule a soma total das vendas realizadas por todos os vendedores.

- Determine a média das vendas.

- Encontre o valor máximo de vendas realizadas por um vendedor e o valor mínimo.

- Organize as vendas em ordem crescente e decrescente.

- Calcule o valor total que a empresa gastará com bônus aos vendedores (considerando que cada vendedor receberá um bônus de 5% sobre suas vendas).

- Determine o índice do vendedor que teve o maior valor de vendas e o índice do vendedor com o menor valor de vendas.

- Quantos vendedores conseguiram realizar vendas acima da média?

- Quais valores únicos de vendas existem, e quantas vezes cada valor aparece?

- Faça a análise de vendedores que superaram a média de vendas e determine os valores únicos de vendas e a quantidade de vezes que cada valor aparece nesse grupo.

In [ ]:
import numpy as np

# Introdução
vendas = np.array([1200, 1500, 1800, 2000, 2500, 1700, 2200, 2100, 2300, 1400, 1600, 1800, 1900, 2100, 2200])

# Resolução do Exercício:

# Cálculo da soma e da média
soma = np.sum(vendas) # soma
media = np.mean(vendas) # média

# Cálculo dos valores máximos e mínimos
maximo = np.max(vendas) # máximo
minimo = np.min(vendas) # mínimo

# Ordenando as vendas
crescente = np.sort(vendas) # ordem crescente
decrescente = np.sort(vendas)[::-1] # ordem decrescente

# Total gasto com bônus de 5%
bonus = np.array([0.05] * len(vendas)) # array com bônus
total_bonus = np.dot(vendas, bonus) # produto escalar

# Índice dos vendedores
maior = np.argmax(vendas) # maior índice
menor = np.argmin(vendas) # menor índice

# Vendedores acima da média
acima = np.count_nonzero(vendas > media) # contagem de vendedores acima da média

# Valores únicos e quantidades
unicos, quantidade = np.unique(vendas, return_counts=True) # contagem normal

# Valores únicos e quantidades a partir de uma média
unicos_media, quantidade_media = np.unique(vendas > media, return_counts=True) # contagem com média

# Prints
print(f'Soma das vendas: {soma}')
print(f'Média das vendas: {media:.2f}')
print(f'Valor máximo das vendas: {maximo}')
print(f'Valor mínimo das vendas: {minimo}')
print(f'Vendas em ordem crescente: {crescente}')
print(f'Vendas em ordem decrescente: {decrescente}')
print(f'Total gasto com bônus de 5%: {total_bonus}')
print(f'Índice do maior vendedor: {maior}')
print(f'Índice do menor vendedor: {menor}')
print(f'Quantidade de vendedores acima da média: {acima}')
print(f'Valores únicos de vendas: {unicos}')
print(f'Quantidade que cada valor aparece: {quantidade}')
print(f'Valores únicos de vendas acima da média: {unicos_media}')
print(f'Quantidade que cada valor de venda acima da média aparece: {quantidade_media}') # True = acima da média

Soma das vendas: 28300
Média das vendas: 1886.67
Valor máximo das vendas: 2500
Valor mínimo das vendas: 1200
Vendas em ordem crescente: [1200 1400 1500 1600 1700 1800 1800 1900 2000 2100 2100 2200 2200 2300
 2500]
Vendas em ordem decrescente: [2500 2300 2200 2200 2100 2100 2000 1900 1800 1800 1700 1600 1500 1400
 1200]
Total gasto com bônus de 5%: 1415.0
Índice do maior vendedor: 4
Índice do menor vendedor: 0
Quantidade de vendedores acima da média: 8
Valores únicos de vendas: [1200 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2500]
Quantidade que cada valor aparece: [1 1 1 1 1 2 1 1 2 2 1 1]
Valores únicos de vendas acima da média: [False  True]
Quantidade que cada valor de venda acima da média aparece: [7 8]


### Exercício 3: Geração de Seeds e Números Aleatórios

Utilizando o módulo `numpy.random`, você deve criar três geradores de números aleatórios (`rng`) com as `seeds` 10, 20 e 30, respectivamente. Com cada seed, você deverá gerar os seguintes dados:

- **Seed 10:** Gere 20 números aleatórios do tipo `float` no intervalo de 100 a 200.

- **Seed 20:** Gere 10 números `inteiros` no intervalo de 20 a 60.

- **Seed 30:** Gere 10 números aleatórios do tipo `float`, utilizando uma distribuição normal com:

    - média = 5

    - desvio padrão = 0.45

In [ ]:
import numpy as np

# Resolução da Seed 10: 

rng = np.random.default_rng(seed=10) # criando seed
valores = rng.random(20) * (200 - 100) + 100 # criando floats aleatórios

print(f'Geração de 20 números aleatórios do tipo float no intervalo de 100 a 200: \n{valores}')

Geração de 20 números aleatórios do tipo float no intervalo de 100 a 200: 
[195.60017096 120.76818101 182.84448853 114.92821231 151.28046164
 113.5919604  168.90364798 184.17477243 142.55089974 195.69260035
 182.53329064 133.82153125 157.57605479 175.33018647 182.7103937
 193.34384709 114.49946949 174.5580211  113.93513939 190.65287561]


In [56]:
import numpy as np

# Resolução da Seed 20: 

rng = np.random.default_rng(seed=20) # criando seed
valores = rng.integers(low=20, high=60, size=10) # criando inteiros aleatórios

print(f'Geração de 10 números inteiros no intervalo de 20 a 60: \n{valores}')

Geração de 10 números inteiros no intervalo de 20 a 60: 
[55 31 30 38 55 24 29 40 29 36]


In [57]:
import numpy as np

# Resolução da Seed 30:

media = 5 # média dos valores
desvio = 0.45 # desvio padrão

rng = np.random.default_rng(seed=30) # criando seed
valores = rng.normal(loc=media, scale=desvio, size=10) # criando floats aleatórios com base na média e desvio padrão

print(f'Geração de 10 números aleatórios do tipo float utilizando uma distribuição normal: \n{valores}')

Geração de 10 números aleatórios do tipo float utilizando uma distribuição normal: 
[5.70858851 5.33447752 4.56355003 4.904598   4.87097154 6.06308851
 4.57554853 5.61910769 5.05543096 5.45983421]


### Exercício 4: Análise de Desempenho de Alunos

Considere um array com as notas finais de 20 alunos em uma disciplina. Com base nessas notas, faça o seguinte:

- Calcule a média geral da turma e retorne:

    - Os índices das notas acima da média.

    - Os valores das notas acima da média.

- Crie um novo array que classifique as notas em:

    - `acima da média`

    - `abaixo da média`

- Aplique as seguintes regras para um novo cálculo de nota ajustada:

    - Alunos com nota menor ou igual a 5 devem receber um aumento de 5%.

    - Alunos com nota entre 5 e 7 (inclusive) devem receber um aumento de 10%.

    - Alunos com nota maior ou igual a 7 devem receber um aumento de 15%.

> Utilize a função `np.where()` para resolver cada uma das partes. <br> Ao final, imprima os arrays gerados e os valores calculados.

In [15]:
import numpy as np

# Introdução
notas = np.array([7.5, 6.2, 8.1, 5.0, 9.3, 4.7, 7.8, 6.5, 5.9, 3.2, 8.7, 6.9, 7.1, 9.0, 4.5, 6.8, 5.4, 8.3, 7.0, 6.0]) # array de notas

# Resolução do Exercício:

# Cálculo da média geral, valores e índices
media = np.mean(notas) # média
indice = np.where(notas > media)[0] # índices acima da média
valores = notas[np.where(notas > media)] # valores acima da média

# Novo array para acima e abaixo da média
acima_abaixo_media = np.where(notas > media, 'acima da média', 'abaixo da média')

# Novos valores das notas com os reajustes
notas = np.where( # encadeamento de wheres
    notas <= 5, notas * 1.05,
    np.where(
        (notas > 5) & (notas < 7), notas * 1.1,
        np.where(
            notas >= 7, notas * 1.15, notas
        )
    )
)

# Prints
print(f'Média das notas: {media}')
print(f'Índice das notas acima da média: {indice}')
print(f'Valores das notas acima da média: {valores}\n')
print(f'Array para saber quais notas estão acima ou abaixo da média: \n{acima_abaixo_media}\n')
print(f'Novo cálculo de reajuste das notas: \n{notas}')

Média das notas: 6.695
Índice das notas acima da média: [ 0  2  4  6 10 11 12 13 15 17 18]
Valores das notas acima da média: [7.5 8.1 9.3 7.8 8.7 6.9 7.1 9.  6.8 8.3 7. ]

Array para saber quais notas estão acima ou abaixo da média: 
['acima da média' 'abaixo da média' 'acima da média' 'abaixo da média'
 'acima da média' 'abaixo da média' 'acima da média' 'abaixo da média'
 'abaixo da média' 'abaixo da média' 'acima da média' 'acima da média'
 'acima da média' 'acima da média' 'abaixo da média' 'acima da média'
 'abaixo da média' 'acima da média' 'acima da média' 'abaixo da média']

Novo cálculo de reajuste das notas: 
[ 8.625  6.82   9.315  5.25  10.695  4.935  8.97   7.15   6.49   3.36
 10.005  7.59   8.165 10.35   4.725  7.48   5.94   9.545  8.05   6.6  ]


### Exercício 5: Reorganizando Produção Semanal de uma Fábrica

Uma fábrica registrou a produção de peças ao longo de 15 dias consecutivos. Os dados foram armazenados em um array unidimensional. Agora, você deve reorganizar esses dados para facilitar a análise semanal.

- Aplique o `reshape()` para transformar o array em uma matriz com 3 semanas (linhas) e 5 dias úteis por semana (colunas).

- Exiba:

    - O array antes e depois do reshape

    - A dimensão e o formato antes e depois do reshape

- Calcule: 

    - A produção total por semana

    - A produção total por dia da semana

    - A média de produção semanal e a média de produção por dia da semana

- Mostre o índice da semana que teve a maior produção

In [32]:
import numpy as np

# Introdução:
numeros = np.array([12, 23, 34, 45, 56, 67, 78, 89, 90, 101, 112, 123, 134, 145, 156]) # produção ao longo de 15 dias

# Resolução do Exercício:

# Aplicando o reshape
producao = np.reshape(numeros, (3, 5))

# Calculando dimensões e formatos
dimensao_antes = np.ndim(numeros) # dimensão antes do reshape
dimensao_reshape = np.ndim(producao) # dimensão depois do reshape
formato_antes = np.shape(numeros) # formato antes do reshape
formato_reshape = np.shape(producao) # formato depois do reshape

# Calculando soma e média de produção total por semana e dia
total_dia = np.sum(producao, axis=0) # produção total por dia
total_semana = np.sum(producao, axis=1) # produção total por semana
media_dia = np.mean(producao, axis=0) # média de produção por dia
media_semana = np.mean(producao, axis=1) # média de produção por semana

# Índice da semana com maior produção
maior_producao = np.argmax(media_semana) # pega o índice da semana com maior produção

# Prints
print(f'Array antes do reshape: {numeros}')
print(f'Array depois do reshape: \n{producao}\n')
print(f'Dimensão antes do reshape: {dimensao_antes}')
print(f'Dimensão depois do reshape: {dimensao_reshape}')
print(f'Formato antes do reshape: {formato_antes}')
print(f'Formato depois do reshape: {formato_reshape}\n')
print(f'Produção total por dia da semana: {total_dia}')
print(f'Produção total por semana: {total_semana}')
print(f'Média de produção por dia da semana: {media_dia}')
print(f'Média de produção por semana: {media_semana}\n')
print(f'Índice da semana que teve a maior produção: {maior_producao}') # índice = 2, logo, foi a semana 3 que teve a maior produção

Array antes do reshape: [ 12  23  34  45  56  67  78  89  90 101 112 123 134 145 156]
Array depois do reshape: 
[[ 12  23  34  45  56]
 [ 67  78  89  90 101]
 [112 123 134 145 156]]

Dimensão antes do reshape: 1
Dimensão depois do reshape: 2
Formato antes do reshape: (15,)
Formato depois do reshape: (3, 5)

Produção total por dia da semana: [191 224 257 280 313]
Produção total por semana: [170 425 670]
Média de produção por dia da semana: [ 63.66666667  74.66666667  85.66666667  93.33333333 104.33333333]
Média de produção por semana: [ 34.  85. 134.]

Índice da semana que teve a maior produção: 2
